name: repository_shared_preferences
description: A shared preferences repository.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.22.1+1
  shared_preferences: ^0.5.3+4
  repository: ^0.0.1
