name: repository_hive
description: "A simple repository-based wrapper around the hive database. 😊"
version: 1.0.3
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/repository

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  hive: ^1.0.0
  repository: ^1.0.3
